hosts: web
tasks:
- name: Update apt-get repo and cache.
  apt:
    update_cache=yes
    force_apt_get=yes
    cache_valid_time=86400
  become: true

- name install nginx
  apt:
    name:
      - nginx

- name: change stirng.
  become: true
  lineinfile:
    path: /var/www/html/index.nginx-debian.html
    regexp: <h1>Welcome to nginx!</h1>
    line: <script> document.write(new Date().toLocaleDateString()); </script>
    state: present
